- name: Setup Google Cloud SDK
  uses: mathrix-education/setup-gcloud@1.1.2
  with:
    # Google Cloud SDK to use. If left null, will use the latest one.
    version: # optional, default is latest
    # The service account key to use, base64-encoded.
    service-account-key: # optional
    # The default Google Cloud project. You can change it later.
    project: # optional, default is auto
    # Install additional components (e.g. beta, gsutil, etc.)
    components: # optional
    # Configure Docker to interact with Google Cloud Container Registry.
    configure-docker: # optional, default is false

